// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/session/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/session/repository.go -destination=internal/mocks/session_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	session "github.com/brunoibarbosa/url-shortener/internal/domain/session"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, s *session.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, s)
}

// FindByRefreshToken mocks base method.
func (m *MockSessionRepository) FindByRefreshToken(ctx context.Context, hash string) (*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRefreshToken", ctx, hash)
	ret0, _ := ret[0].(*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRefreshToken indicates an expected call of FindByRefreshToken.
func (mr *MockSessionRepositoryMockRecorder) FindByRefreshToken(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRefreshToken", reflect.TypeOf((*MockSessionRepository)(nil).FindByRefreshToken), ctx, hash)
}

// Revoke mocks base method.
func (m *MockSessionRepository) Revoke(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockSessionRepositoryMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockSessionRepository)(nil).Revoke), ctx, id)
}

// MockBlacklistRepository is a mock of BlacklistRepository interface.
type MockBlacklistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlacklistRepositoryMockRecorder
	isgomock struct{}
}

// MockBlacklistRepositoryMockRecorder is the mock recorder for MockBlacklistRepository.
type MockBlacklistRepositoryMockRecorder struct {
	mock *MockBlacklistRepository
}

// NewMockBlacklistRepository creates a new mock instance.
func NewMockBlacklistRepository(ctrl *gomock.Controller) *MockBlacklistRepository {
	mock := &MockBlacklistRepository{ctrl: ctrl}
	mock.recorder = &MockBlacklistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlacklistRepository) EXPECT() *MockBlacklistRepositoryMockRecorder {
	return m.recorder
}

// IsRevoked mocks base method.
func (m *MockBlacklistRepository) IsRevoked(ctx context.Context, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRevoked", ctx, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRevoked indicates an expected call of IsRevoked.
func (mr *MockBlacklistRepositoryMockRecorder) IsRevoked(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRevoked", reflect.TypeOf((*MockBlacklistRepository)(nil).IsRevoked), ctx, token)
}

// Revoke mocks base method.
func (m *MockBlacklistRepository) Revoke(ctx context.Context, token string, expiresIn time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, token, expiresIn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockBlacklistRepositoryMockRecorder) Revoke(ctx, token, expiresIn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockBlacklistRepository)(nil).Revoke), ctx, token, expiresIn)
}

// MockSessionQueryRepository is a mock of SessionQueryRepository interface.
type MockSessionQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionQueryRepositoryMockRecorder is the mock recorder for MockSessionQueryRepository.
type MockSessionQueryRepositoryMockRecorder struct {
	mock *MockSessionQueryRepository
}

// NewMockSessionQueryRepository creates a new mock instance.
func NewMockSessionQueryRepository(ctrl *gomock.Controller) *MockSessionQueryRepository {
	mock := &MockSessionQueryRepository{ctrl: ctrl}
	mock.recorder = &MockSessionQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionQueryRepository) EXPECT() *MockSessionQueryRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSessionQueryRepository) List(ctx context.Context, params session.ListSessionsParams) ([]session.ListSessionsDTO, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]session.ListSessionsDTO)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSessionQueryRepositoryMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSessionQueryRepository)(nil).List), ctx, params)
}
