// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/session/encrypter.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/session/encrypter.go -destination=internal/mocks/session_encrypter_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionEncrypter is a mock of SessionEncrypter interface.
type MockSessionEncrypter struct {
	ctrl     *gomock.Controller
	recorder *MockSessionEncrypterMockRecorder
	isgomock struct{}
}

// MockSessionEncrypterMockRecorder is the mock recorder for MockSessionEncrypter.
type MockSessionEncrypterMockRecorder struct {
	mock *MockSessionEncrypter
}

// NewMockSessionEncrypter creates a new mock instance.
func NewMockSessionEncrypter(ctrl *gomock.Controller) *MockSessionEncrypter {
	mock := &MockSessionEncrypter{ctrl: ctrl}
	mock.recorder = &MockSessionEncrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionEncrypter) EXPECT() *MockSessionEncrypterMockRecorder {
	return m.recorder
}

// HashRefreshToken mocks base method.
func (m *MockSessionEncrypter) HashRefreshToken(token string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashRefreshToken", token)
	ret0, _ := ret[0].(string)
	return ret0
}

// HashRefreshToken indicates an expected call of HashRefreshToken.
func (mr *MockSessionEncrypterMockRecorder) HashRefreshToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashRefreshToken", reflect.TypeOf((*MockSessionEncrypter)(nil).HashRefreshToken), token)
}
