// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/url/shortcode.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/url/shortcode.go -destination=internal/mocks/shortcode_generator_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShortCodeGenerator is a mock of ShortCodeGenerator interface.
type MockShortCodeGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockShortCodeGeneratorMockRecorder
	isgomock struct{}
}

// MockShortCodeGeneratorMockRecorder is the mock recorder for MockShortCodeGenerator.
type MockShortCodeGeneratorMockRecorder struct {
	mock *MockShortCodeGenerator
}

// NewMockShortCodeGenerator creates a new mock instance.
func NewMockShortCodeGenerator(ctrl *gomock.Controller) *MockShortCodeGenerator {
	mock := &MockShortCodeGenerator{ctrl: ctrl}
	mock.recorder = &MockShortCodeGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortCodeGenerator) EXPECT() *MockShortCodeGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockShortCodeGenerator) Generate(length int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", length)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockShortCodeGeneratorMockRecorder) Generate(length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockShortCodeGenerator)(nil).Generate), length)
}
