// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/session/state.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/session/state.go -destination=internal/mocks/state_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStateService is a mock of StateService interface.
type MockStateService struct {
	ctrl     *gomock.Controller
	recorder *MockStateServiceMockRecorder
	isgomock struct{}
}

// MockStateServiceMockRecorder is the mock recorder for MockStateService.
type MockStateServiceMockRecorder struct {
	mock *MockStateService
}

// NewMockStateService creates a new mock instance.
func NewMockStateService(ctrl *gomock.Controller) *MockStateService {
	mock := &MockStateService{ctrl: ctrl}
	mock.recorder = &MockStateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateService) EXPECT() *MockStateServiceMockRecorder {
	return m.recorder
}

// DeleteState mocks base method.
func (m *MockStateService) DeleteState(ctx context.Context, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteState indicates an expected call of DeleteState.
func (mr *MockStateServiceMockRecorder) DeleteState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteState", reflect.TypeOf((*MockStateService)(nil).DeleteState), ctx, state)
}

// GenerateState mocks base method.
func (m *MockStateService) GenerateState(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateState", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateState indicates an expected call of GenerateState.
func (mr *MockStateServiceMockRecorder) GenerateState(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateState", reflect.TypeOf((*MockStateService)(nil).GenerateState), ctx)
}

// ValidateState mocks base method.
func (m *MockStateService) ValidateState(ctx context.Context, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateState indicates an expected call of ValidateState.
func (mr *MockStateServiceMockRecorder) ValidateState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateState", reflect.TypeOf((*MockStateService)(nil).ValidateState), ctx, state)
}
