// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/url/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/url/repository.go -destination=internal/mocks/url_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	url "github.com/brunoibarbosa/url-shortener/internal/domain/url"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockURLRepository is a mock of URLRepository interface.
type MockURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryMockRecorder
	isgomock struct{}
}

// MockURLRepositoryMockRecorder is the mock recorder for MockURLRepository.
type MockURLRepositoryMockRecorder struct {
	mock *MockURLRepository
}

// NewMockURLRepository creates a new mock instance.
func NewMockURLRepository(ctrl *gomock.Controller) *MockURLRepository {
	mock := &MockURLRepository{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepository) EXPECT() *MockURLRepositoryMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockURLRepository) Exists(ctx context.Context, shortCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, shortCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockURLRepositoryMockRecorder) Exists(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockURLRepository)(nil).Exists), ctx, shortCode)
}

// FindByShortCode mocks base method.
func (m *MockURLRepository) FindByShortCode(ctx context.Context, shortCode string) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShortCode", ctx, shortCode)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShortCode indicates an expected call of FindByShortCode.
func (mr *MockURLRepositoryMockRecorder) FindByShortCode(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShortCode", reflect.TypeOf((*MockURLRepository)(nil).FindByShortCode), ctx, shortCode)
}

// Save mocks base method.
func (m *MockURLRepository) Save(ctx context.Context, arg1 *url.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockURLRepositoryMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockURLRepository)(nil).Save), ctx, arg1)
}

// SoftDelete mocks base method.
func (m *MockURLRepository) SoftDelete(ctx context.Context, id, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockURLRepositoryMockRecorder) SoftDelete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockURLRepository)(nil).SoftDelete), ctx, id, userID)
}

// MockURLCacheRepository is a mock of URLCacheRepository interface.
type MockURLCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockURLCacheRepositoryMockRecorder is the mock recorder for MockURLCacheRepository.
type MockURLCacheRepositoryMockRecorder struct {
	mock *MockURLCacheRepository
}

// NewMockURLCacheRepository creates a new mock instance.
func NewMockURLCacheRepository(ctrl *gomock.Controller) *MockURLCacheRepository {
	mock := &MockURLCacheRepository{ctrl: ctrl}
	mock.recorder = &MockURLCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLCacheRepository) EXPECT() *MockURLCacheRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockURLCacheRepository) Delete(ctx context.Context, shortCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, shortCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockURLCacheRepositoryMockRecorder) Delete(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURLCacheRepository)(nil).Delete), ctx, shortCode)
}

// Exists mocks base method.
func (m *MockURLCacheRepository) Exists(ctx context.Context, shortCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, shortCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockURLCacheRepositoryMockRecorder) Exists(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockURLCacheRepository)(nil).Exists), ctx, shortCode)
}

// FindByShortCode mocks base method.
func (m *MockURLCacheRepository) FindByShortCode(ctx context.Context, shortCode string) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShortCode", ctx, shortCode)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShortCode indicates an expected call of FindByShortCode.
func (mr *MockURLCacheRepositoryMockRecorder) FindByShortCode(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShortCode", reflect.TypeOf((*MockURLCacheRepository)(nil).FindByShortCode), ctx, shortCode)
}

// Save mocks base method.
func (m *MockURLCacheRepository) Save(ctx context.Context, arg1 *url.URL, expires time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1, expires)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockURLCacheRepositoryMockRecorder) Save(ctx, arg1, expires any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockURLCacheRepository)(nil).Save), ctx, arg1, expires)
}

// MockURLQueryRepository is a mock of URLQueryRepository interface.
type MockURLQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockURLQueryRepositoryMockRecorder is the mock recorder for MockURLQueryRepository.
type MockURLQueryRepositoryMockRecorder struct {
	mock *MockURLQueryRepository
}

// NewMockURLQueryRepository creates a new mock instance.
func NewMockURLQueryRepository(ctrl *gomock.Controller) *MockURLQueryRepository {
	mock := &MockURLQueryRepository{ctrl: ctrl}
	mock.recorder = &MockURLQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLQueryRepository) EXPECT() *MockURLQueryRepositoryMockRecorder {
	return m.recorder
}

// ListByUserID mocks base method.
func (m *MockURLQueryRepository) ListByUserID(ctx context.Context, userID uuid.UUID, params url.ListURLsParams) ([]url.ListURLsDTO, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, params)
	ret0, _ := ret[0].([]url.ListURLsDTO)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockURLQueryRepositoryMockRecorder) ListByUserID(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockURLQueryRepository)(nil).ListByUserID), ctx, userID, params)
}
