// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/url/encrypter.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/url/encrypter.go -destination=internal/mocks/url_encrypter_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockURLEncrypter is a mock of URLEncrypter interface.
type MockURLEncrypter struct {
	ctrl     *gomock.Controller
	recorder *MockURLEncrypterMockRecorder
	isgomock struct{}
}

// MockURLEncrypterMockRecorder is the mock recorder for MockURLEncrypter.
type MockURLEncrypterMockRecorder struct {
	mock *MockURLEncrypter
}

// NewMockURLEncrypter creates a new mock instance.
func NewMockURLEncrypter(ctrl *gomock.Controller) *MockURLEncrypter {
	mock := &MockURLEncrypter{ctrl: ctrl}
	mock.recorder = &MockURLEncrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLEncrypter) EXPECT() *MockURLEncrypterMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockURLEncrypter) Decrypt(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockURLEncrypterMockRecorder) Decrypt(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockURLEncrypter)(nil).Decrypt), arg0)
}

// Encrypt mocks base method.
func (m *MockURLEncrypter) Encrypt(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockURLEncrypterMockRecorder) Encrypt(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockURLEncrypter)(nil).Encrypt), arg0)
}
