// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/user/encrypter.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/user/encrypter.go -destination=internal/mocks/user_encrypter_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserPasswordEncrypter is a mock of UserPasswordEncrypter interface.
type MockUserPasswordEncrypter struct {
	ctrl     *gomock.Controller
	recorder *MockUserPasswordEncrypterMockRecorder
	isgomock struct{}
}

// MockUserPasswordEncrypterMockRecorder is the mock recorder for MockUserPasswordEncrypter.
type MockUserPasswordEncrypterMockRecorder struct {
	mock *MockUserPasswordEncrypter
}

// NewMockUserPasswordEncrypter creates a new mock instance.
func NewMockUserPasswordEncrypter(ctrl *gomock.Controller) *MockUserPasswordEncrypter {
	mock := &MockUserPasswordEncrypter{ctrl: ctrl}
	mock.recorder = &MockUserPasswordEncrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPasswordEncrypter) EXPECT() *MockUserPasswordEncrypterMockRecorder {
	return m.recorder
}

// CheckPassword mocks base method.
func (m *MockUserPasswordEncrypter) CheckPassword(arg0, arg1 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPassword", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckPassword indicates an expected call of CheckPassword.
func (mr *MockUserPasswordEncrypterMockRecorder) CheckPassword(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPassword", reflect.TypeOf((*MockUserPasswordEncrypter)(nil).CheckPassword), arg0, arg1)
}

// HashPassword mocks base method.
func (m *MockUserPasswordEncrypter) HashPassword(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockUserPasswordEncrypterMockRecorder) HashPassword(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockUserPasswordEncrypter)(nil).HashPassword), arg0)
}
